services:
  - type: web
    name: kubenko-production-studio
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    region: oregon
    node: 20
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kubenko-database
          property: connectionString

databases:
  - name: kubenko-database
    databaseName: kubenko_production
    plan: free